-- Arquivo legado desativado por segurança e privacidade.
--
-- A versão anterior continha nomes comerciais, telefones e endereços usados
-- como demonstração. Esses registros não devem ser republicados nem aplicados
-- em ambientes novos.
--
-- Para preparar o banco, use exclusivamente as migrações canônicas:
--
--   supabase db push
--
-- Os dados de demonstração para desenvolvimento permanecem em
-- lib/data/mockData.ts e são carregados somente fora de produção, ou quando
-- NEXT_PUBLIC_ENABLE_DEMO_DATA=true for configurado explicitamente.
